/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examples;

import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgarchilin
 */
public class PoliceDB extends javax.swing.JFrame {

    public Object[] ob;
    private int row;
    private String[][] OfficerInfoCopy = new String[row][6];

    /**
     * Creates new form PoliceDB
     */
    public PoliceDB() {
        initComponents();
        try {
            //  SQLConnections.getConnection();
            SQLConnections.RetrieveInformaiton();
            SQLConnections.OfficerInformation();
            SQLConnections.OfficerAssigments();
            SQLConnections.callerInformaiton();
            SQLConnections.IncidentReportInfo();
            TableUpdate();
            TableUpdate2();
            
            CallerTable();
        } catch (Exception ex) {
            Logger.getLogger(PoliceDB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        SearchButton = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        MakeCallName = new javax.swing.JTextField();
        MakeCallDescritpion = new javax.swing.JTextField();
        SubmitCall = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        Description = new javax.swing.JTextField();
        CallerName = new javax.swing.JTextField();
        PoliceCode = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        GetCall = new javax.swing.JButton();
        SendReport = new javax.swing.JButton();
        Location = new javax.swing.JTextField();
        IncidentType = new javax.swing.JTextField();
        Priority = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        callNumberText = new javax.swing.JTextField();
        CallerIDsave = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 800));
        setPreferredSize(new java.awt.Dimension(747, 600));

        jTabbedPane1.setMaximumSize(new java.awt.Dimension(500, 500));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(747, 800));

        jPanel3.setMaximumSize(new java.awt.Dimension(295, 295));
        jPanel3.setPreferredSize(new java.awt.Dimension(295, 295));

        jLabel1.setText("Officer Location ");

        jLabel2.setText("Officer Assignment");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Badge Number", "Name", "Status", "Type Of Officer", "Position", "Location", "CarNumber"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        SearchButton.setText("Locaton");
        SearchButton.setToolTipText("");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        jButton4.setText("Search");
        jButton4.setToolTipText("");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83)
                        .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(SearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Officer Info", jPanel3);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        MakeCallName.setText("Name");
        MakeCallName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakeCallNameActionPerformed(evt);
            }
        });

        MakeCallDescritpion.setText("Descritpion");

        SubmitCall.setText("Submit");
        SubmitCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitCallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SubmitCall)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(MakeCallName)
                        .addComponent(MakeCallDescritpion, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)))
                .addContainerGap(423, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(MakeCallName, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MakeCallDescritpion, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubmitCall)
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("Make Call", jPanel4);

        Description.setText("Description");
        Description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionActionPerformed(evt);
            }
        });

        CallerName.setText("Caller Name");
        CallerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CallerNameActionPerformed(evt);
            }
        });

        PoliceCode.setText("Police Code");
        PoliceCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PoliceCodeActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Caller", "Time", "Hold"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        GetCall.setText("Get Call");
        GetCall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetCallActionPerformed(evt);
            }
        });

        SendReport.setText("Send Report");
        SendReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendReportActionPerformed(evt);
            }
        });

        Location.setText("Location");
        Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationActionPerformed(evt);
            }
        });

        IncidentType.setText("Incident Type");

        Priority.setText("Priority");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        callNumberText.setText("Call Number");

        CallerIDsave.setText("Caller ID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CallerName, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(Location, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(Description, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(PoliceCode, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(SendReport)
                    .addComponent(Priority)
                    .addComponent(CallerIDsave)
                    .addComponent(IncidentType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(callNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(GetCall))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GetCall)
                            .addComponent(callNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IncidentType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CallerIDsave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CallerName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Location, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PoliceCode, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(Priority, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SendReport)
                        .addGap(38, 38, 38)))
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("Operator", jPanel2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5294, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dispatcher", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 5323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("OfficerInfo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationActionPerformed

    private void CallerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CallerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CallerNameActionPerformed

    private void DescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionActionPerformed

    private void GetCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetCallActionPerformed
        int id = Integer.parseInt(callNumberText.getText().trim());
        GetCall(id);
    }//GEN-LAST:event_GetCallActionPerformed

    private void MakeCallNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakeCallNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MakeCallNameActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.getDataVector().removeAllElements();
        for (int i = 0; i < SQLConnections.officersList.size(); i++) {
            if (SearchButton.getText().equals(SQLConnections.officersList.get(i).getLocation())) {
                String name = SQLConnections.officersList.get(i).getName();
                String status = SQLConnections.officersList.get(i).getStatus();
                String officerType = SQLConnections.officersList.get(i).getOfficerType();
                String position = SQLConnections.officersList.get(i).getPosition();
                String location = SQLConnections.officersList.get(i).getLocation();
                int badgeNumber = SQLConnections.officersList.get(i).getBadgeNumber();
                int carNumber = SQLConnections.officersList.get(i).getCarNumber();
                Object[] tablerow = {Integer.toString(badgeNumber), name, status, officerType,
                    position, location,
                    Integer.toString(carNumber)};
                model.addRow(tablerow);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        for (int i = 0; i < SQLConnections.officersList.size(); i++) {
            if (SearchButton.getText().equals(SQLConnections.officersList.get(i).getLocation())) {
                String name = SQLConnections.officersList.get(i).getName();
                String status = SQLConnections.officersList.get(i).getStatus();
                String officerType = SQLConnections.officersList.get(i).getOfficerType();
                String position = SQLConnections.officersList.get(i).getPosition();
                String location = SQLConnections.officersList.get(i).getLocation();
                int badgeNumber = SQLConnections.officersList.get(i).getBadgeNumber();
                int carNumber = SQLConnections.officersList.get(i).getCarNumber();
                Object[] tablerow = {Integer.toString(badgeNumber), name, status, officerType,
                     position, location,
                    Integer.toString(carNumber)};
                model.addRow(tablerow);
            }
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void GetCall(int id) {
        try {
            for (int i = 0; i < SQLConnections.callerList.size(); i++) {
                if (SQLConnections.callerList.get(i).getCallerID() == id) {
                 //   System.out.println(SQLConnections.callerList.get(i).getCallerID());
                 //   JOptionPane.showMessageDialog(null, "Caller Name : "+SQLConnections.callerList.get(i).getName()+ "\n"
                 //   +"Description: \n"+SQLConnections.callerList.get(i).getDescription());
                   JFrame frame = new JFrame("Test Frame");
        frame.setDefaultCloseOperation( JFrame.EXIT_ON_CLOSE );
        JLabel label = new JLabel("My label", SwingConstants.CENTER);
         label.setText("Caller Name : "+SQLConnections.callerList.get(i).getName()+ "\n"
                    +"Description: \n"+SQLConnections.callerList.get(i).getDescription());
         
        frame.add(label);
        frame.setSize( new Dimension( 500, 200 ));

        frame.setVisible(true);
                }
            }
        } catch (Exception e) {
            System.out.println("Does not exist");
        }

    }

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        TableUpdate2();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void SubmitCallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitCallActionPerformed
        String name = MakeCallName.getText();
        String description = MakeCallDescritpion.getText();
        InsertSQL.InsertCall(name, description);
           SQLConnections.callerInformaiton();
            CallerTable();
    }//GEN-LAST:event_SubmitCallActionPerformed

    private void SendReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendReportActionPerformed
       String callid  = CallerIDsave.getText().trim();
        String name = CallerName.getText();
        String description = Description.getText();
        String location = Location.getText();
        String incidentType = IncidentType.getText();
        String priority = Priority.getText();
        String policeCode = PoliceCode.getText();
        System.out.print(incidentType + " "  + name + " "+ location + " "  + 
              description + " "  +  Integer.parseInt(policeCode.trim()));
        InsertSQL.IncidentReport( incidentType,  name,  location, 
              description,  Integer.parseInt(policeCode));
        InsertSQL.Priority(priority, InsertSQL.getIncidentReportPK());
        InsertSQL.ReicieveCallIncidentReport( Integer.parseInt(callid),InsertSQL.getIncidentReportPK() );
    System.out.println("done");
    }//GEN-LAST:event_SendReportActionPerformed

    private void PoliceCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PoliceCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PoliceCodeActionPerformed

    private void Insert(){
        
    }
    
    private  void SendReport(){
       
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PoliceDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PoliceDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PoliceDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PoliceDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PoliceDB().setVisible(true);
            }
        });
    }

    public void TableUpdate() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        for (int i = 0; i < SQLConnections.users.size(); i++) {
            String name = SQLConnections.users.get(i).getName();

            Object[] tablerow = {name, Integer.toString(i)};
            model.addRow(tablerow);
        }
    }

    public void TableUpdate2() {

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
       for (int i = 0; i < SQLConnections.officersList.size(); i++) {
                String name = SQLConnections.officersList.get(i).getName();
                String status = SQLConnections.officersList.get(i).getStatus();
                String officerType = SQLConnections.officersList.get(i).getOfficerType();
                String position = SQLConnections.officersList.get(i).getPosition();
                String location = SQLConnections.officersList.get(i).getLocation();
                int badgeNumber = SQLConnections.officersList.get(i).getBadgeNumber();
                int carNumber = SQLConnections.officersList.get(i).getCarNumber();
                Object[] tablerow = {Integer.toString(badgeNumber), name, status, officerType,
                     position, location,
                    Integer.toString(carNumber)};
                model.addRow(tablerow);
            
        }
    }

    public void CallerTable() {
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        // model.getDataVector().removeAllElements();
        model.setRowCount(0);

        for (int i = 0; i < SQLConnections.callerList.size(); i++) {
            String hold = "hold";
            //String name = SQLConnections.users.get(i).getName();
            String name = SQLConnections.callerList.get(i).getName();
            String status = SQLConnections.callerList.get(i).getDescription();

            if (SQLConnections.callerList.get(i).isHoldStatus()) {
                hold = "active";
            }
            int callerId = SQLConnections.callerList.get(i).getCallerID();

            Object[] row = {callerId, status, hold};
            model.addRow(row);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CallerIDsave;
    private javax.swing.JTextField CallerName;
    private javax.swing.JTextField Description;
    private javax.swing.JButton GetCall;
    private javax.swing.JTextField IncidentType;
    private javax.swing.JTextField Location;
    private javax.swing.JTextField MakeCallDescritpion;
    private javax.swing.JTextField MakeCallName;
    private javax.swing.JTextField PoliceCode;
    private javax.swing.JTextField Priority;
    private javax.swing.JTextField SearchButton;
    private javax.swing.JButton SendReport;
    private javax.swing.JToggleButton SubmitCall;
    private javax.swing.JTextField callNumberText;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
